version: "3"
services:
  app:
    build: ./app
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - "./:/webapp"
      - "~/.ssh:/root/.ssh"
      - "~/.gitconfig:/root/.gitconfig"
  php-xdebug:
    build: ./php-xdebug
    ports:
      - 9000:9000
      - 80:10081
