version: "3"
services:
  app:
    image: node:14
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - "./:/webapp"
  php-xdebug:
    build: ./php-xdebug
    ports:
      - 9000:9000
      - 80:10081
